//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroFocus.Adm.Octane.VisualStudio {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class OctanePluginSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static OctanePluginSettings defaultInstance = ((OctanePluginSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new OctanePluginSettings())));
        
        public static OctanePluginSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EntityFields {
            get {
                return ((string)(this["EntityFields"]));
            }
            set {
                this["EntityFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection SearchHistory {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SearchHistory"]));
            }
            set {
                this["SearchHistory"] = value;
            }
        }
    }
}
